### ISSUE TITLE
dependencie error jdbc-jt400 

### ISSUE THREAD

**Issue by mac-manu** [ecraft/sequel-jdbc-as400#9]
`jdbc-jt400-9.1.1/lib/jt400.jar:1: Invalid char `\x03' in expression (SyntaxError)`

any ideas ?

**Comment by olleolleolle** [comment]
@mac-manu Is this change relevant? Removed support for JRuby 1.7.x: https://github.com/ecraft/sequel-jdbc-as400/pull/5

**Comment by perlun** [comment]
@mac-manu Also, are you using JRuby or plain MRI? (silly question but it _looks_ like your Ruby is trying to parse the `.jar` as a Ruby file instead of a Java JAR file.)

**Comment by olleolleolle** [comment]
@mac-manu Can this issue be closed?
